set -e 

python utils/match_peaks.py -r ./results/Train\Train_ff'_predictions.csv
python utils/match_peaks.py -r ./results/Train\Train_ff_2000_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_ff_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_ff_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_ff_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_ff_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_gru'_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_gru_2000_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_gru_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_gru_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_gru_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_gru_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lr_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lr_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lr_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lr_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lstm'_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lstm_120_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lstm_2000_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lstm_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lstm_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lstm_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Train\Train_lstm_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_ff'_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_ff_2000_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_ff_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_ff_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_ff_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_ff_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_gru'_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_gru_2000_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_gru_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_gru_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_gru_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_gru_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lr_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lr_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lr_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lr_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lstm'_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lstm_120_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lstm_2000_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lstm_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lstm_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lstm_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Val\Val_lstm_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_ff'_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_ff_2000_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_ff_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_ff_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_ff_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_ff_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_gru'_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_gru_2000_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_gru_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_gru_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_gru_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_gru_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lr_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lr_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lr_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lr_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lstm'_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lstm_120_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lstm_2000_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lstm_hi_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lstm_hi_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lstm_lo_predictions.csv 
python utils/match_peaks.py -r ./results/Test\Test_lstm_predictions.csv 
